"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, Check, Clock3, MapPin, MessageCircle, ParkingCircle, Phone } from "lucide-react";
import { faqs, journey, needs, professionals, treatments } from "@/data/content";
import { Brand, Header } from "@/components/site/header";
import { PatientNeeds } from "@/components/site/patient-needs";
import { TreatmentCard } from "@/components/site/treatment-card";
import { VideoSection } from "@/components/site/video-section";
import { BeforeAfterSlider } from "@/components/site/before-after-slider";
import { Metrics, WhyAura } from "@/components/site/metrics";

const booking = "#contato";

function ContactForm() {
  const [sent, setSent] = useState(false);
  return <form className="contact-form" onSubmit={e => { e.preventDefault(); setSent(true); }}><div className="field-row"><label>Nome<input required name="name" placeholder="Como podemos chamar você?" /></label><label>WhatsApp<input required name="phone" type="tel" placeholder="(11) 99999-9999" /></label></div><label>Como podemos ajudar?<select name="interest" defaultValue=""><option value="" disabled>Selecione uma necessidade</option>{needs.map(n => <option key={n.label}>{n.label}</option>)}</select></label><label>Mensagem <span>opcional</span><textarea name="message" rows={3} placeholder="Conte-nos brevemente o que você busca." /></label><button className="button button-light" type="submit">Solicitar contato <ArrowRight size={17} /></button>{sent && <p className="form-success" role="status"><Check size={16} /> Solicitação demonstrativa recebida. Em um site real, a equipe entraria em contato.</p>}</form>;
}

export default function AuraExperience() {
  useEffect(() => { const items = document.querySelectorAll<HTMLElement>("[data-reveal]"); const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && entry.target.classList.add("revealed")), { threshold: .12 }); items.forEach(item => observer.observe(item)); return () => observer.disconnect(); }, []);
  return <><Header /><main>
    <section className="hero" id="inicio"><Image src="/images/hero-aura.png" alt="Dentista da AURA apresentando um diagnóstico digital a uma paciente" fill priority sizes="100vw" className="hero-image" /><div className="hero-wash" /><div className="hero-content"><p className="eyebrow light">Saúde · Estética · Confiança</p><h1>Um novo padrão<br />em odontologia.</h1><p className="hero-copy">Odontologia de alta precisão para quem busca saúde, estética e confiança em cada detalhe.</p><div className="hero-actions"><a className="button button-light" href={booking}>Agendar avaliação</a><a className="text-link light" href="#manifesto">Conhecer a AURA <ArrowRight size={16} /></a></div></div><a href="#manifesto" className="scroll-note">Descubra a AURA <ArrowDown size={16} /></a><span className="hero-index">AURA / 01</span></section>
    <section className="manifesto section" id="manifesto" data-reveal><div><p className="eyebrow">Nossa filosofia</p><p className="section-number">01</p></div><div><h2>Precisão para cuidar.<br /><em>Sensibilidade para transformar.</em></h2><p>Na AURA, cada sorriso começa com escuta. Tecnologia amplia nossa visão; experiência orienta cada escolha; e a naturalidade define o resultado.</p></div></section>
    <PatientNeeds />
    <section className="treatments section" id="tratamentos" data-reveal><div className="section-head"><div><p className="eyebrow">Tratamentos</p><h2>Cuidado integrado,<br />resultados naturais.</h2></div><p>Especialidades que se conectam em um único planejamento.</p></div><div className="treatment-list">{treatments.map(t => <TreatmentCard key={t.title} treatment={t} />)}</div></section>
    <VideoSection />
    <section className="results section-dark" id="resultados" data-reveal><div className="section-head light"><div><p className="eyebrow light">Resultados</p><h2>Naturalidade<br />que se percebe.</h2></div><p>Caso ilustrativo para demonstração do projeto. Resultados clínicos reais variam conforme cada paciente.</p></div><BeforeAfterSlider /><div className="case-meta"><div><span>Caso 01</span><strong>Harmonização do sorriso</strong></div><div><span>Abordagem</span><strong>Planejamento digital + cerâmica</strong></div><div><span>Objetivo</span><strong>Proporção, luminosidade e naturalidade</strong></div></div></section>
    <section className="technology section" data-reveal><div className="tech-lead"><p className="eyebrow">Tecnologia a serviço do cuidado</p><h2>Mais informação.<br />Decisões mais precisas.</h2><p>Na AURA, tecnologia não substitui o olhar humano. Ela torna o diagnóstico mais claro, o planejamento mais previsível e a experiência mais confortável.</p></div><div className="tech-orbit" aria-hidden="true"><div className="orbit"><span>AURA</span></div><small>Diagnóstico conectado</small></div><div className="tech-points"><article><span>01</span><h3>Veja antes de começar</h3><p>Escaneamento e simulação digital ajudam você a compreender possibilidades com clareza.</p></article><article><span>02</span><h3>Menos etapas, mais conforto</h3><p>Fluxos digitais reduzem moldagens, ajustes e o tempo necessário em consultório.</p></article><article><span>03</span><h3>Um plano exclusivamente seu</h3><p>Dados clínicos e imagem trabalham juntos para orientar escolhas mais seguras.</p></article></div></section>
    <WhyAura />
    <Metrics />
    <section className="specialists section" id="especialistas" data-reveal><div className="section-head"><div><p className="eyebrow">Especialistas</p><h2>Excelência é<br />um trabalho coletivo.</h2></div><p>Um time multidisciplinar que compartilha casos, decisões e um mesmo padrão de cuidado.</p></div><div className="team-visual"><Image src="/images/especialistas-aura.png" alt="Equipe demonstrativa de especialistas da AURA" fill sizes="100vw" /></div><div className="profiles">{professionals.map((p, i) => <article key={p.name}><span>0{i + 1}</span><h3>{p.name}</h3><strong>{p.role}</strong><p>{p.formation}</p><small>{p.cro}</small></article>)}</div><p className="demo-note">Profissionais, formações, registros e métricas apresentados são fictícios e fazem parte deste projeto demonstrativo.</p></section>
    <section className="journey section-dark" data-reveal><div className="section-head light"><div><p className="eyebrow light">Sua jornada</p><h2>Clareza em cada etapa.</h2></div><p>Você sabe o que acontece, por que acontece e qual é o próximo passo.</p></div><ol className="journey-list">{journey.map((step, i) => <li key={step}><span>{String(i + 1).padStart(2, "0")}</span><strong>{step}</strong></li>)}</ol></section>
    <section className="testimonial section" data-reveal><p className="quote-mark">“</p><blockquote>O que mais me marcou foi entender cada escolha antes do tratamento. O resultado ficou exatamente como eu queria: bonito, discreto e com a minha identidade.</blockquote><div><strong>Mariana F.</strong><span>Paciente de reabilitação estética · depoimento fictício</span><small>★★★★★ 5,0</small></div></section>
    <section className="clinic" id="clinica" data-reveal><div className="clinic-image"><Image src="/images/clinica-aura.png" alt="Recepção contemporânea da clínica AURA" fill sizes="100vw" /></div><div className="clinic-panel"><p className="eyebrow light">A clínica</p><h2>Arquitetura pensada<br />para desacelerar.</h2><p>Privacidade, luz natural e um ambiente sereno. Cada espaço foi concebido para acolher você com conforto, discrição e segurança.</p><div className="clinic-facts"><span><strong>06</strong> salas privativas</span><span><strong>360°</strong> fluxo digital</span><span><strong>100%</strong> acessível</span></div></div></section>
    <section className="experience section" data-reveal><div><p className="eyebrow">Experiência AURA</p><h2>O cuidado começa<br />antes do tratamento.</h2></div><div className="experience-grid"><article><span>01</span><h3>Tempo para ouvir</h3><p>Consultas sem pressa, com espaço para dúvidas e decisões conscientes.</p></article><article><span>02</span><h3>Privacidade real</h3><p>Atendimento reservado, organização de agenda e comunicação discreta.</p></article><article><span>03</span><h3>Conforto em detalhes</h3><p>Ambientes calmos, controle de sensibilidade e acompanhamento próximo.</p></article></div></section>
    <section className="faq section" data-reveal><div><p className="eyebrow">Perguntas frequentes</p><h2>Antes da sua<br />primeira visita.</h2></div><div className="faq-list">{faqs.map(([q, a], i) => <details key={q}><summary><span>0{i + 1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
    <section className="location section" data-reveal><div className="map-card"><span className="map-pin"><MapPin /></span><span className="road r1"/><span className="road r2"/><span className="road r3"/><small>Jardins · São Paulo</small></div><div className="location-copy"><p className="eyebrow">Localização</p><h2>Perto de tudo.<br />Longe da pressa.</h2><p>Alameda dos Ipês, 280 — Jardins<br />São Paulo · SP · 01414-000</p><ul><li><ParkingCircle /> Estacionamento com manobrista</li><li><MapPin /> A 6 minutos da Av. Paulista</li><li><Clock3 /> Segunda a sexta, 8h às 19h</li></ul><p className="demo-note">Endereço fictício para fins demonstrativos.</p></div></section>
    <section className="contact section-dark" id="contato"><div className="contact-copy"><p className="eyebrow light">Primeiro contato</p><h2>Seu próximo sorriso<br /><em>começa aqui.</em></h2><p>Conte-nos o que você busca. Nossa equipe retornará para organizar uma primeira conversa.</p><div className="contact-direct"><span><Phone size={17} /> (11) 4000-2028</span><span><MessageCircle size={17} /> WhatsApp demonstrativo</span></div></div><ContactForm /></section>
  </main><footer><div><Brand /><p>Odontologia de alta precisão, com sensibilidade em cada detalhe.</p></div><div><strong>Navegue</strong><a href="#especialidades">Especialidades</a><a href="#especialistas">Especialistas</a><a href="#resultados">Resultados</a></div><div><strong>Visite</strong><span>Alameda dos Ipês, 280<br />Jardins · São Paulo</span><span>Seg—Sex · 8h—19h</span></div><div><strong>Contato</strong><a href="#contato">WhatsApp</a><a href="#contato">Instagram</a><a href="#contato">contato@aura.demo</a></div><div className="footer-bottom"><span>© 2026 AURA · Projeto demonstrativo fictício</span><span>Privacidade · Termos · Acessibilidade</span></div></footer><div className="mobile-bar"><a href="#contato"><MessageCircle size={17} /> WhatsApp</a><a href={booking}>Agendar avaliação</a></div></>;
}
